apiVersion: v1
kind: ConfigMap
metadata:
  name: kortes-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kortes.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
