apiVersion: v1
kind: Service
metadata:
  name: kortes-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kortes.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: kortes-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
