apiVersion: v1
kind: Service
metadata:
  name: kortes-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kortes.labels" . | nindent 4 }}
spec:
  selector:
    app: kortes-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
