"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-06-14 23:39:12.873607
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_token'), 'devices', ['token'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('lane', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_table('avatars',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatars_device_id'), 'avatars', ['device_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('avatar_id', sa.String(length=32), nullable=False),
    sa.Column('status_fast', sa.String(length=16), nullable=False),
    sa.Column('script', sa.JSON(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_avatar_id'), 'videos', ['avatar_id'], unique=False)
    op.create_index(op.f('ix_videos_device_id'), 'videos', ['device_id'], unique=False)
    op.create_table('voices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('avatar_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voices_avatar_id'), 'voices', ['avatar_id'], unique=False)
    op.create_index(op.f('ix_voices_device_id'), 'voices', ['device_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('avatar_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('bundle', sa.JSON(), nullable=True),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_avatar_id'), 'plans', ['avatar_id'], unique=False)
    op.create_index(op.f('ix_plans_device_id'), 'plans', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_device_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_avatar_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_voices_device_id'), table_name='voices')
    op.drop_index(op.f('ix_voices_avatar_id'), table_name='voices')
    op.drop_table('voices')
    op.drop_index(op.f('ix_videos_device_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_avatar_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_avatars_device_id'), table_name='avatars')
    op.drop_table('avatars')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_devices_token'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
